import dotenv from 'dotenv';
import neo4j from 'neo4j-driver';
dotenv.config({ path: new URL('../.env', import.meta.url) });
const { COGNODB_URI, COGNODB_USERNAME, COGNODB_PASSWORD } = process.env;
if (![COGNODB_URI, COGNODB_USERNAME, COGNODB_PASSWORD].every(Boolean)) { console.error('Missing CognoDB credentials. Copy .env.example to .env and fill it in.'); process.exit(1); }
const driver=neo4j.driver(COGNODB_URI,neo4j.auth.basic(COGNODB_USERNAME,COGNODB_PASSWORD));
const skills = [
['programming-fundamentals','Programming Fundamentals','Core','Beginner'],['html','HTML','Frontend','Beginner'],['css','CSS','Frontend','Beginner'],['javascript','JavaScript','Frontend','Intermediate'],['typescript','TypeScript','Frontend','Intermediate'],['react','React','Frontend','Intermediate'],['nextjs','Next.js','Frontend','Advanced'],['nodejs','Node.js','Backend','Intermediate'],['express','Express.js','Backend','Intermediate'],['rest-api','REST APIs','Backend','Intermediate'],['databases','Databases','Data','Intermediate'],['postgresql','PostgreSQL','Data','Intermediate'],['mongodb','MongoDB','Data','Intermediate'],['java','Java','Backend','Intermediate'],['oop','Object-Oriented Programming','Core','Intermediate'],['data-structures','Data Structures','Core','Intermediate'],['spring-boot','Spring Boot','Backend','Advanced'],['python','Python','Backend','Beginner'],['pandas','Pandas','Data','Intermediate'],['numpy','NumPy','Data','Intermediate'],['sql','SQL','Data','Intermediate'],['data-visualization','Data Visualization','Data','Intermediate'],['etl','ETL Pipelines','Data','Advanced'],['airflow','Apache Airflow','Data','Advanced'],['machine-learning','Machine Learning','AI','Advanced'],['deep-learning','Deep Learning','AI','Advanced'],['tensorflow','TensorFlow','AI','Advanced'],['linux','Linux','DevOps','Intermediate'],['git','Git','DevOps','Beginner'],['docker','Docker','DevOps','Intermediate'],['kubernetes','Kubernetes','DevOps','Advanced'],['cloud','Cloud Computing','Cloud','Intermediate'],['aws','AWS','Cloud','Advanced'],['ci-cd','CI/CD','DevOps','Advanced'],['networking','Networking','Security','Intermediate'],['cybersecurity','Cybersecurity','Security','Advanced'],['testing','Testing','Quality','Intermediate'],['system-design','System Design','Architecture','Advanced'],['statistics','Statistics','Data','Intermediate'],['nlp','Natural Language Processing','AI','Advanced']
].map(([id,name,category,difficulty])=>({id,name,category,difficulty,description:`Practical ${name} knowledge for building modern software.`,seed:'careergraph'}));
const roles=[
['frontend-developer','Frontend Developer','Build accessible, responsive browser experiences.','Engineering','High',['html','css','javascript','typescript','react','git','testing']],['backend-developer','Backend Developer','Build reliable APIs, services and data layers.','Engineering','High',['nodejs','express','rest-api','databases','postgresql','git','testing']],['full-stack-developer','Full Stack Developer','Deliver product features across the web stack.','Engineering','High',['html','css','javascript','react','nodejs','express','databases','git']],['java-developer','Java Developer','Develop maintainable JVM services.','Engineering','Medium',['java','oop','data-structures','spring-boot','rest-api','postgresql','git']],['python-developer','Python Developer','Create automation and backend applications with Python.','Engineering','High',['python','oop','data-structures','rest-api','postgresql','git','testing']],['react-developer','React Developer','Create polished component-driven interfaces.','Engineering','High',['javascript','typescript','react','nextjs','testing','git']],['nodejs-developer','Node.js Developer','Build scalable JavaScript server applications.','Engineering','High',['javascript','nodejs','express','rest-api','mongodb','git']],['devops-engineer','DevOps Engineer','Automate delivery and operate cloud platforms.','Infrastructure','High',['linux','git','docker','kubernetes','cloud','aws','ci-cd']],['cloud-engineer','Cloud Engineer','Design and operate resilient cloud infrastructure.','Infrastructure','High',['linux','networking','cloud','aws','docker','ci-cd']],['data-analyst','Data Analyst','Turn data into trustworthy decisions.','Data','High',['sql','statistics','pandas','data-visualization','git']],['data-engineer','Data Engineer','Build dependable pipelines and analytical datasets.','Data','High',['python','sql','postgresql','etl','airflow','cloud','git']],['machine-learning-engineer','Machine Learning Engineer','Productionize predictive models and experiments.','AI','High',['python','statistics','numpy','pandas','machine-learning','tensorflow','docker']],['software-engineer','Software Engineer','Design, build and maintain valuable software products.','Engineering','High',['programming-fundamentals','oop','data-structures','git','testing','system-design']],['cybersecurity-analyst','Cybersecurity Analyst','Protect systems through detection and security practice.','Security','High',['linux','networking','cybersecurity','python','git']],['ai-ml-engineer','AI/ML Engineer','Build AI systems from data to deployment.','AI','High',['python','statistics','numpy','machine-learning','deep-learning','nlp','cloud']]
].map(([id,name,description,category,demandLevel,required])=>({id,name,description,category,demandLevel,required,seed:'careergraph'}));
const projects=['portfolio-site','ecommerce-dashboard','task-api','social-api','job-board','weather-app','expense-tracker','java-bank-api','spring-store','python-automation','data-dashboard','sales-analysis','etl-pipeline','ml-classifier','image-classifier','nlp-sentiment','dockerized-api','k8s-deployment','cloud-terraform','security-audit'].map((id,i)=>({id,name:id.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join(' '),description:`A realistic ${id.replaceAll('-',' ')} portfolio project.`,difficulty:['Beginner','Intermediate','Advanced'][i%3],githubUrl:`https://github.com/topics/${id}`,seed:'careergraph'}));
const resources=['MDN Web Docs','React Learn','Node.js Learn','Express Guide','PostgreSQL Tutorial','MongoDB University','Spring Guides','Python Tutorial','Pandas Documentation','NumPy Learn','Kubernetes Basics','Docker Get Started','AWS Skill Builder','Git Book','OWASP Top 10','Google ML Crash Course','TensorFlow Tutorials','freeCodeCamp','Khan Academy Statistics','Apache Airflow Docs','Next.js Learn','Microsoft Learn Azure','Coursera Data Engineering','Linux Journey','REST API Design'].map((title,i)=>({id:`resource-${i+1}`,title,type:i%3===0?'Documentation':i%3===1?'Course':'Interactive tutorial',url:i===0?'https://developer.mozilla.org/':i===13?'https://git-scm.com/book/en/v2':`https://www.google.com/search?q=${encodeURIComponent(title)}`,provider:['MDN','Official docs','freeCodeCamp','Google'][i%4],difficulty:['Beginner','Intermediate','Advanced'][i%3],seed:'careergraph'}));
const users=[['maya','Maya Patel',['html','css','javascript','git']],['liam','Liam Chen',['python','sql','pandas','statistics']],['sofia','Sofia Martin',['java','oop','data-structures','git']],['noah','Noah Williams',['linux','git','docker','cloud']],['ava','Ava Johnson',['python','numpy','machine-learning']],['ethan','Ethan Brown',['html','css','javascript','react','nodejs']],['zara','Zara Khan',['sql','postgresql','etl']],['oliver','Oliver Smith',['linux','networking','cybersecurity']]].map(([id,name,userSkills])=>({id,name,userSkills,seed:'careergraph'}));
const prerequisite=[['programming-fundamentals','javascript'],['programming-fundamentals','python'],['programming-fundamentals','java'],['html','css'],['css','javascript'],['javascript','typescript'],['javascript','react'],['react','nextjs'],['javascript','nodejs'],['nodejs','express'],['express','rest-api'],['databases','postgresql'],['databases','mongodb'],['java','oop'],['oop','data-structures'],['java','spring-boot'],['python','pandas'],['python','numpy'],['pandas','machine-learning'],['numpy','machine-learning'],['statistics','machine-learning'],['machine-learning','deep-learning'],['deep-learning','tensorflow'],['machine-learning','nlp'],['linux','git'],['linux','docker'],['docker','kubernetes'],['linux','cloud'],['cloud','aws'],['git','ci-cd'],['linux','networking'],['networking','cybersecurity'],['sql','etl'],['etl','airflow'],['sql','data-visualization']];
const projectSkills=[['portfolio-site',['html','css','javascript','react']],['ecommerce-dashboard',['react','typescript','rest-api']],['task-api',['nodejs','express','postgresql']],['social-api',['nodejs','express','mongodb']],['job-board',['react','nodejs','postgresql']],['weather-app',['javascript','rest-api']],['expense-tracker',['react','nodejs','databases']],['java-bank-api',['java','spring-boot','postgresql']],['spring-store',['java','spring-boot','rest-api']],['python-automation',['python','git']],['data-dashboard',['sql','pandas','data-visualization']],['sales-analysis',['sql','statistics','pandas']],['etl-pipeline',['python','sql','etl','airflow']],['ml-classifier',['python','numpy','machine-learning']],['image-classifier',['python','tensorflow','deep-learning']],['nlp-sentiment',['python','nlp','machine-learning']],['dockerized-api',['docker','nodejs','express']],['k8s-deployment',['docker','kubernetes','ci-cd']],['cloud-terraform',['cloud','aws','ci-cd']],['security-audit',['linux','networking','cybersecurity']]];
const resourceSkills=skills.map((s,i)=>[s.id,resources[i%resources.length].id]);
const session=driver.session({defaultAccessMode:neo4j.session.WRITE});
try { await driver.verifyConnectivity(); console.log('Connected to CognoDB.');
 try { await session.executeWrite(tx=>tx.run('CREATE CONSTRAINT careergraph_role_id IF NOT EXISTS FOR (n:Role) REQUIRE n.id IS UNIQUE')); await session.executeWrite(tx=>tx.run('CREATE CONSTRAINT careergraph_skill_id IF NOT EXISTS FOR (n:Skill) REQUIRE n.id IS UNIQUE')); console.log('Graph constraints verified.'); } catch { console.log('Constraint creation is not available on this CognoDB tier; continuing with MERGE.'); }
 await session.executeWrite(tx=>tx.run(`MATCH (n {seed:'careergraph'}) DETACH DELETE n`));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MERGE (n:Skill {id:row.id}) SET n += row',{rows:skills}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MERGE (n:Role {id:row.id}) SET n += row REMOVE n.required',{rows:roles}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MERGE (n:Project {id:row.id}) SET n += row',{rows:projects}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MERGE (n:Resource {id:row.id}) SET n += row',{rows:resources}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MERGE (n:User {id:row.id}) SET n += row REMOVE n.userSkills',{rows:users}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MATCH (r:Role {id:row.id}) UNWIND row.required AS skillId MATCH (s:Skill {id:skillId}) MERGE (r)-[:REQUIRES {importance:"Core"}]->(s)',{rows:roles}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MATCH (a:Skill {id:row[0]}),(b:Skill {id:row[1]}) MERGE (a)-[:PREREQUISITE_OF]->(b)',{rows:prerequisite}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MATCH (p:Project {id:row[0]}) UNWIND row[1] AS skillId MATCH (s:Skill {id:skillId}) MERGE (p)-[:DEMONSTRATES]->(s)',{rows:projectSkills}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MATCH (s:Skill {id:row[0]}),(r:Resource {id:row[1]}) MERGE (s)-[:LEARNED_FROM]->(r)',{rows:resourceSkills}));
 await session.executeWrite(tx=>tx.run('UNWIND $rows AS row MATCH (u:User {id:row.id}) UNWIND row.userSkills AS skillId MATCH (s:Skill {id:skillId}) MERGE (u)-[:HAS_SKILL {level:"Working knowledge"}]->(s)',{rows:users}));
 await session.executeWrite(tx=>tx.run('MATCH (p:Project)-[:DEMONSTRATES]->(s:Skill)<-[:REQUIRES]-(r:Role) WITH p,r,count(s) AS shared WHERE shared >= 2 MERGE (p)-[:RECOMMENDED_FOR]->(r)'));
 await session.executeWrite(tx=>tx.run('MATCH (a:Role)-[:REQUIRES]->(s:Skill)<-[:REQUIRES]-(b:Role) WHERE a.id < b.id WITH a,b,count(s) AS shared WHERE shared >= 3 MERGE (a)-[:RELATED_TO]->(b)'));
 const result=await session.run(`MATCH (n {seed:'careergraph'}) RETURN labels(n)[0] AS label,count(*) AS count ORDER BY label`); console.table(result.records.map(r=>({label:r.get('label'),count:r.get('count').toNumber()}))); console.log('Seed complete.');
} finally { await session.close(); await driver.close(); }
